# Generated by Django 3.2.4 on 2021-06-28 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='medicine',
        ),
    ]
