# Generated by Django 3.2.4 on 2021-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cart_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='summry',
            field=models.TextField(blank=True, null=True),
        ),
    ]
